CREATE TABLE [dbo].[PLAYER_INFO] (
    [PLAYER_ID]     INT            IDENTITY (1001, 1) NOT NULL,
    [PLAYER_NAME]   VARCHAR (500)  NOT NULL,
    [PLAYER_EMAIL]  NVARCHAR (500) NOT NULL,
    [PLAYER_PASS]   NVARCHAR (200) NOT NULL,
    [PLAYER_GENDER] VARCHAR (100)  NOT NULL,
    [PLAYER_AGE]    NVARCHAR (100)  NOT NULL,
    [PLAYER_PIC]    NVARCHAR (100)   NULL,
    PRIMARY KEY CLUSTERED ([PLAYER_ID] ASC)
);

