CREATE TABLE PLAYER_INFO (
    PLAYER_ID int IDENTITY(1001,1) PRIMARY KEY,
    PLAYER_NAME VARCHAR(500) NOT NULL,
    PLAYER_EMAIL NVARCHAR(500) NOT NULL,
    PLAYER_PASS NVARCHAR(200) NOT NULL,
    PLAYER_GENDER VARCHAR(100) NOT NULL,
    PLAYER_AGE nvarchar(10) NOT NULL,
    
    );
    select PLAYER_ID FROM PLAYER_INFO order by PLAYER_ID desc;